
# @name scratchpad
POST http://localhost:3000/api/v2/scratchpad HTTP/1.1
accept: application/json
content-type: application/json

{
  "name": "system_errors",  
  "level": "error",  
  "message": "Database connection failed",  
  "meta": {  
    "errorCode": "DB_CONN_ERR",  
    "stack": "Error: Connection timeout at db.connect (db.js:42:15)",  
    "timestamp": "2025-03-04T18:32:00.456Z"  
  }  
}

###
# @name scratchpad
GET http://localhost:3000/api/v2/scratchpad HTTP/1.1
accept: application/json
content-type: application/json

