import { z } from "zod";

// Define the Zod schema for MinErrorLog
const MinErrorLogSchema = z.object({
  id: z.string().optional(), // Auto-generated by database
  timestamp: z.string().datetime(), // Ensures valid ISO 8601 format
  environment: z.enum(["production", "staging", "development", "test"]),
  severity: z.string().min(1), // Ensure non-empty severity
  pageUrl: z.string().url(), // Validates as a proper URL
  errorMessage: z.string().min(1), // Ensure a non-empty error message
  stackTrace: z.string().optional(), // Optional stack trace
  projectId: z.string().optional(), // ObjectId as string
});
type MinErrorLog = z.infer<typeof MinErrorLogSchema>;
export { MinErrorLogSchema, type MinErrorLog };
